;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        clean-aindent--bsunindent
        helm-M-x
        helm-confirm-and-exit-minibuffer
        indent-for-tab-command
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
